name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create and Publish Release
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: '16'
      - name: Set Version
        run: echo "${{ github.ref }}" > version.txt
      - name: Make Distribution - macOS
        if: matrix.platform == 'macos-latest'
        run: >-
          ./gradlew -Prelease createDistributable
          cd ./build/compose/binaries/main/app
          REF=${{ github.ref }}
          tar -czf ExtraHoursExporter-${REF#refs/tags/v}.tgz ExtraHoursExporter.app
      - name: Make Distribution - Windows
        if: matrix.platform == 'windows-latest'
        run: ./gradlew -Prelease package
      - name: Create Release
        if: matrix.platform == 'macos-latest'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Upload Package
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./build/compose/binaries/main/app/*.tgz
            ./build/compose/binaries/main/msi/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
